services:
  server:
    ports:
      - 3000:3000
    image: registry.gitlab.com/piazzer/piazzer-server
    build:
      context: backend
    volumes:
      - ./backend:/usr/local/app
    working_dir: /usr/local/app

  client:
    ports:
      - 3000:3000
    image: registry.gitlab.com/piazzer/piazzer-front-end
    build:
      context: frontend
    volumes:
      - ./frontend:/usr/local/app
    working_dir: /usr/local/app

  db1:
    image: postgres
    restart: always
    environment:
       - POSTGRES_PASSWORD=root
       - POSTGRES_DB=piazzer
       - POSTGRES_USER=postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data:
    driver: local
  redis:
    driver: local
