services:
  main:
    build: ./
    ports:
      - 3000:3000

  db:
    image: postgres
    restart: always
    environment:
       - POSTGRES_PASSWORD=root
       - POSTGRES_DB=piazzer
       - POSTGRES_USER=postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data:
    driver: local
  redis:
    driver: local